feat(ci): Add sync-source-mirrors job after successful x86 build
terragraph/meta-terragraph pull request #28
Opened 2022-08-04 05:32 UTC by MatthewWEdwards

## Prerequisites

- [x] I have read the [Contributing Guidelines](../blob/main/CONTRIBUTING.md).
- [x] I have read the [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
- [x] If this is a non-trivial change, I have already opened an accompanying Issue.
- [x] If applicable, I have included documentation updates alongside my code changes.

## Description

Add downloaded tarballs to the shared `source_mirrors` filesystem on
self-hosted runners. Also add BB_GENERATE_MIRROR_TARBALLS = "1" to
bitbake configuration by default for all meta-layers so that tarballs
are generated.

## Test Plan

1. Delete facebook/openr GitHub tarball from source mirrors
2. Clear openr build artifacts from sstate-cache
3. Run workflow: https://github.com/terragraph/meta-terragraph/actions/runs/2794158940
4. See new openr tarball in source_mirrors: 

```
ubuntu@ip-10-0-20-186:~/source_mirrors$ ls -lh | grep openr -A 2 -B 2
-rw-r--r-- 1 ubuntu ubuntu  6.7M May 10 18:49 git2_github.com.facebook.fbzmq.git.tar.gz
-rw-r--r-- 1 ubuntu ubuntu   52M May 10 18:49 git2_github.com.facebook.folly.git.tar.gz
-rw-rw-r-- 1 ubuntu ubuntu   30M Aug  4 05:18 git2_github.com.facebook.openr.git.tar.gz
-rw-r--r-- 1 ubuntu ubuntu   21M May 10 18:49 git2_github.com.facebook.proxygen.git.tar.gz
-rw-r--r-- 1 ubuntu ubuntu  6.9M May 10 18:49 git2_github.com.facebook.wangle.git.tar.gz
```

2022-08-04 18:04 UTC, elludraon requested changes
Is there a reason you're enabling `BB_GENERATE_MIRROR_TARBALLS` by default instead of only in this workflow? For regular user builds the mirror tarballs would just waste disk space. If you do choose to keep it like this then `BB_GENERATE_MIRROR_TARBALLS` should also be deleted from `facebook/conf/allow-all-networks.conf`.

2022-08-04 18:04 UTC, elludraon commented on .github/workflows/terragraph-image-x86.yml
> +        -exec cp {} $SELF_HOSTED_RUNNER_HOME/source_mirrors \;
"cp -v" ?

2022-08-09 15:18 UTC, MatthewWEdwards commented on .github/workflows/terragraph-image-x86.yml
> +    - name: Upload Downloads
Changed "downloads" -> "sources" because they're not all tarballs.

2022-08-09 15:53 UTC, MatthewWEdwards commented
- Add new configuration file setting `BB_GENERATE_MIRROR_TARBALLS` to `1`
- Rename "downloads" artifact to "sources"
- Add `-v` flag to `cp`

2022-08-09 17:14 UTC, elludraon approved these changes

2022-08-09 17:35 UTC, merged